query1 = "CREATE TABLE `frav_ABC`.`logitech_halogeno_data` (" \
       "`id` INT AUTO_INCREMENT," \
       "`clase` INT NOT NULL," \
       "`file` VARCHAR(255) NOT NULL," \
       "`locateFace` INT NOT NULL," \
       "`faceConfidence` REAL NOT NULL," \
       "`locateEyes` INT NOT NULL," \
       "`eye0Confidence` REAL NOT NULL," \
       "`eye1Confidence` REAL NOT NULL," \
       "`age` INT NOT NULL," \
       "`backgroundUniformity` REAL NOT NULL," \
       "`chin` REAL NOT NULL," \
       "`crown` REAL NOT NULL," \
       "`deviationFromFrontalPose` REAL NOT NULL," \
       "`deviationFromUniformLighting` REAL NOT NULL," \
       "`ear0` REAL NOT NULL," \
       "`ear1` REAL NOT NULL," \
       "`ethnicityAsian` REAL NOT NULL," \
       "`ethnicityBlack` REAL NOT NULL," \
       "`ethnicityWhite` REAL NOT NULL," \
       "`exposure` REAL NOT NULL," \
       "`eye0X` REAL NOT NULL," \
       "`eye0Y` REAL NOT NULL," \
       "`eye0GazeFrontal` REAL NOT NULL," \
       "`eye0Open` REAL NOT NULL," \
       "`eye0Red` REAL NOT NULL," \
       "`eye0Tinted` REAL NOT NULL," \
       "`eye1X` REAL NOT NULL," \
       "`eye1Y` REAL NOT NULL," \
       "`eye1GazeFrontal` REAL NOT NULL," \
       "`eye1Open` REAL NOT NULL," \
       "`eye1Red` REAL NOT NULL," \
       "`eye1Tinted` REAL NOT NULL," \
       "`eyeDistance` REAL NOT NULL," \
       "`faceCenterX` REAL NOT NULL," \
       "`faceCenterY` REAL NOT NULL," \
       "`glasses` REAL NOT NULL," \
       "`grayScaleDensity` INT NOT NULL," \
       "`height` INT NOT NULL," \
       "`hotSpots` INT NOT NULL," \
       "`isColor` INT NOT NULL," \
       "`isMale` REAL NOT NULL," \
       "`lengthOfHead` REAL NOT NULL," \
       "`mouthClosed` REAL NOT NULL," \
       "`naturalSkinColour` REAL NOT NULL," \
       "`numberOfFaces` INT NOT NULL," \
       "`poseAngleRoll` REAL NOT NULL," \
       "`sharpness` REAL NOT NULL," \
       "`width` INT NOT NULL," \
       "`widthOfHead` REAL NOT NULL," \
       "`ISO_19794_5_EyesGazeFrontalBestPractice` INT NOT NULL," \
       "`ISO_19794_5_EyesNotRedBestPractice` INT NOT NULL," \
       "`ISO_19794_5_EyesOpenBestPractice` INT NOT NULL," \
       "`ISO_19794_5_GoodExposure` INT NOT NULL," \
       "`ISO_19794_5_GoodGrayScaleProfile` INT NOT NULL," \
       "`ISO_19794_5_GoodVerticalFacePosition` INT NOT NULL," \
       "`ISO_19794_5_HasNaturalSkinColour` INT NOT NULL," \
       "`ISO_19794_5_HorizontallyCenteredFace` INT NOT NULL," \
       "`ISO_19794_5_ImageWidthToHeightBestPractice` INT NOT NULL," \
       "`ISO_19794_5_IsBackgroundUniformBestPractice` INT NOT NULL," \
       "`ISO_19794_5_IsBestPractice` INT NOT NULL," \
       "`ISO_19794_5_IsCompliant` INT NOT NULL," \
       "`ISO_19794_5_IsFrontal` INT NOT NULL," \
       "`ISO_19794_5_IsFrontalBestPractice` INT NOT NULL," \
       "`ISO_19794_5_IsLightingUniform` INT NOT NULL," \
       "`ISO_19794_5_IsSharp` INT NOT NULL," \
       "`ISO_19794_5_LengthOfHead` INT NOT NULL," \
       "`ISO_19794_5_LengthOfHeadBestPractice` INT NOT NULL," \
       "`ISO_19794_5_MouthClosedBestPractice` INT NOT NULL," \
       "`ISO_19794_5_NoHotSpots` INT NOT NULL," \
       "`ISO_19794_5_NoTintedGlasses` INT NOT NULL," \
       "`ISO_19794_5_OnlyOneFaceVisible` INT NOT NULL," \
       "`ISO_19794_5_Resolution` INT NOT NULL," \
       "`ISO_19794_5_ResolutionBestPractice` INT NOT NULL," \
       "`ISO_19794_5_WidthOfHead` INT NOT NULL," \
       "`ISO_19794_5_WidthOfHeadBestPractice` INT NOT NULL," \
       "`Features_Ethnicity` INT NOT NULL," \
       "`Features_Gender` INT NOT NULL," \
       "`Features_WearsGlasses` INT NOT NULL," \
       "PRIMARY KEY (`id`));"
